### ISSUE TITLE
P2P

### ISSUE THREAD

**Issue by AbdelrhmanAmin** [marilirulita/capstone-html-css#2]
.carousel-indicators => Maybe change the color or the background color because It's hard to see it.
Add space between buttons in the hot ad.
Maybe put the Hot Ad left button on the white place not on the image itself.

**Comment by vichuge** [comment]
![image](https://user-images.githubusercontent.com/20563252/103778843-734f6980-4ff8-11eb-91e6-914db0308cf4.png)

The url project is different.

**Comment by VanessaAoki** [comment]
Mar, this project looks AMAZING! Congratulations!

I do have a little comment to make. In the head of your HTML file, for organization purposes, the script and link tags should be grouped up, for example, line 7 should be line 8 instead, so all the links will be together before the scripts.

Also, on a side note, script tags can be placed both in the head tags or at the end of the body. Usually, for bigger projects, they are set up in the end for loading speed purposes!

Keep up the great job
